### ISSUE TITLE
Dragon Age: Inquisition

### ISSUE THREAD

**Issue by libcg** [libcg/grvk#38]
Meta-issue for Dragon Age: Inquisition.
- [x] Working
- [ ] Tessellation
- [ ] ???

**Comment by Nerellus** [comment]
Logs from current master ( 6a0e4d860f55eb4f5cdef00e97bd95bca788505b )
[grvk.log](https://github.com/libcg/grvk/files/7692511/grvk.log)
[grvk_axl.log](https://github.com/libcg/grvk/files/7692512/grvk_axl.log)

Crashes during launch.

**Comment by libcg** [comment]
Thanks, I have a branch that makes it boot, I can go in-game but it crashes during the first dialog scene.

**Comment by libcg** [comment]
@Nerellus the game should boot and go ingame with this build: https://github.com/libcg/grvk/suites/4708213536/artifacts/129087929 (make sure tessellation is disabled in the settings). However I'm seeing a crash in the first dialog scene when starting a new game.

**Comment by Nerellus** [comment]
Unfortunately I still don't make it to the menu, I get 
`wine: Unhandled page fault on execute access to 0000000000000000 at address 0000000000000000 (thread 0520), starting debugger...` at launch now.
[origin.log](https://github.com/libcg/grvk/files/7744196/origin.log)
[grvk.log](https://github.com/libcg/grvk/files/7744197/grvk.log) (with GRVK_LOG_LEVEL=trace)
[grvk_axl.log](https://github.com/libcg/grvk/files/7744289/grvk_axl.log)

**Comment by libcg** [comment]
@Nerellus try this build: https://github.com/libcg/grvk/actions/runs/1605043031 I fixed a few validation errors.

The in-game crash I mentioned earlier is caused by unhandled tessellation shaders.

**Comment by Nerellus** [comment]
I still get the page fault at launch with d9ca03e74ef21e6699342a23338fcd77d4b02a15.

**Comment by plasticbomb1986** [comment]
OS: Arch Linux
KERNEL: 5.16.0-rc6-1-mainline
CPU: AMD Ryzen 7 3800XT 8-Core
GPU: AMD Radeon RX Vega (vega10, LLVM 13.0.0, DRM 3.44, 5.16.0-rc6-1-mainline)
GPU DRIVER: 4.6 Mesa 22.0.0-devel (git-222487fabe)
RAM: 32 GB
GRVK: d9ca03e

[steam-1222690.log](https://github.com/libcg/grvk/files/7776070/steam-1222690.log)
[grvk.log](https://github.com/libcg/grvk/files/7776071/grvk.log)
[grvk_axl.log](https://github.com/libcg/grvk/files/7776072/grvk_axl.log)

Result.
![IMG_20211225_180602](https://user-images.githubusercontent.com/26345407/147390097-8f1bcaa8-ec9a-4a76-b334-0d22c144d546.jpg)

Game starts up with GRVK, nicely goes through the menu, race and what type of character its gonna be, then the heper cards, and than..... The picture above. Have to shoot down the processes through ssh and reboot the computer to get back the screen.

**Comment by plasticbomb1986** [comment]
So, just ran it again, made sure everything i know of what can cause my system to hang up is off (PBO, no OC nothing, just default system).

Same result. Settings: Low preset, fullhd, mantle.
Its loading into world, walked away from the moment when first you can controll the character, up halfway on the mountain side while i was checking the game works with dxvk. Then there made a save, and loading back there. The game loads in the first few frame, and crash. i think its crashing the gpu (resulting in the same screen as above), probably tries to do something stupid, or not yet implemented, and pulls down the whole 3d engine, and probably mutter too. If i SSH in and do a sudo reboot, console comes back and shows the normal messages as its shutting down modules, and does the reboot process. 

One note: I think GRVK needs a check on what vulkan implementation its loading in. As im building mesa-git, RADV, lavapipe, Intel, vrtio all gets build, and for some reason grvk tries to load in a different one then what it should on my amd vega gpus, until i remove all the others and only leave radv in vulkan/icd.d.

logs with GRVK_LOG_LEVEL=trace
[dragonagecrashgrvk.zip](https://github.com/libcg/grvk/files/7834694/dragonagecrashgrvk.zip)

**Comment by plasticbomb1986** [comment]
Hoi! New month, new testruns. Game loads into menu, but on high settings it crashes as its loading the game, on low it loads in the first few frames, (like5-10) and than its crashing.

Logs:
high settings:
[grvk_axl.log](https://github.com/libcg/grvk/files/8308991/grvk_axl.log)
[high settings-grvk.zip](https://github.com/libcg/grvk/files/8308992/high.settings-grvk.zip)
[high settings-steam-1222690.zip](https://github.com/libcg/grvk/files/8308993/high.settings-steam-1222690.zip)
[Origin_d3d11.log](https://github.com/libcg/grvk/files/8308994/Origin_d3d11.log)
[Origin_dxgi.log](https://github.com/libcg/grvk/files/8308995/Origin_dxgi.log)
low settings:
[grvk_axl.log](https://github.com/libcg/grvk/files/8308996/grvk_axl.log)
[low settings- steam-1222690.zip](https://github.com/libcg/grvk/files/8308997/low.settings-.steam-1222690.zip)
[Origin_d3d11.log](https://github.com/libcg/grvk/files/8308998/Origin_d3d11.log)
[Origin_dxgi.log](https://github.com/libcg/grvk/files/8308999/Origin_dxgi.log)

Not sure why, but the low settings grvk.log github does not accept it, none compressed its obviously to big, but even compressed its reject it, so ive uploaded it to my google drive: https://drive.google.com/file/d/1E1CGZ_aiBmWTEASUTZMroE4AeaSbFg0a/view?usp=sharing

**Comment by libcg** [comment]
@plasticbomb1986 the crash you were seeing should be fixed by https://github.com/libcg/grvk/commit/02ae2a5db29a8aab3b1787da844dd8db241a3172

**Comment by libcg** [comment]
The game should be playable as of 2bb8b8e (build available here: https://github.com/libcg/grvk/suites/9530381740/artifacts/452852535)

Make sure to disable tessellation in the settings to make the terrain visible. Also, there's a rendering bug where shadows disappear depending on the camera position.
